/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.feib.popov.bigjava.lessons.ch18.FontFrame;

import java.awt.Font;

/**
 *
 * @author popov
 */
public class FontViewer extends javax.swing.JFrame {
    private String fontName;
    private int fontSize;
    private int fontStyle;
    
    private static final int SMALL_SIZE = 24;
    private static final int MEDIUM_SIZE = 28;
    private static final int LARGE_SIZE = 32;
    
    /**
     * Creates new form FontViewer
     */
    public FontViewer() {
        initComponents();
        askComponents();
        applyFont();
    }
    
    private void askComponents() {
        fontName = (String)this.jComboBoxFont.getSelectedItem();
        
        if (this.jRadioButtonSizeSmall.isSelected()) {
            fontSize = SMALL_SIZE;
        } else if (this.jRadioButtonSizeMedium.isSelected()) {
            fontSize = MEDIUM_SIZE;
        } else if (this.jRadioButtonSizeLarge.isSelected()) {
            fontSize = LARGE_SIZE;
        }
        
        fontStyle = 
                ((this.jCheckBoxStyleItalic.isSelected()) ? 
                    Font.ITALIC : 0) 
                + 
                ((this.jCheckBoxStyleBold.isSelected()) ? 
                    Font.BOLD : 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        SizeButtons = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jLabelText = new javax.swing.JLabel();
        jPanelFont = new javax.swing.JPanel();
        jComboBoxFont = new javax.swing.JComboBox();
        jPanelStyle = new javax.swing.JPanel();
        jCheckBoxStyleItalic = new javax.swing.JCheckBox();
        jCheckBoxStyleBold = new javax.swing.JCheckBox();
        jPanelSize = new javax.swing.JPanel();
        jRadioButtonSizeSmall = new javax.swing.JRadioButton();
        jRadioButtonSizeMedium = new javax.swing.JRadioButton();
        jRadioButtonSizeLarge = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelText.setText("Big Java");

        jPanelFont.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxFont.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Serif", "SansSerif", "Monospaced" }));
        jComboBoxFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxListener(evt);
            }
        });

        javax.swing.GroupLayout jPanelFontLayout = new javax.swing.GroupLayout(jPanelFont);
        jPanelFont.setLayout(jPanelFontLayout);
        jPanelFontLayout.setHorizontalGroup(
            jPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFontLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jComboBoxFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanelFontLayout.setVerticalGroup(
            jPanelFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelStyle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Style"));
        jPanelStyle.setToolTipText("");

        jCheckBoxStyleItalic.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jCheckBoxStyleItalic.setText("Italic");
        jCheckBoxStyleItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicButtonClicked(evt);
            }
        });

        jCheckBoxStyleBold.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxStyleBold.setText("Bold");
        jCheckBoxStyleBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoldButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStyleLayout = new javax.swing.GroupLayout(jPanelStyle);
        jPanelStyle.setLayout(jPanelStyleLayout);
        jPanelStyleLayout.setHorizontalGroup(
            jPanelStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStyleLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxStyleBold)
                    .addComponent(jCheckBoxStyleItalic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStyleLayout.setVerticalGroup(
            jPanelStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStyleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jCheckBoxStyleItalic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxStyleBold)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSize.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Size"));
        jPanelSize.setToolTipText("");

        SizeButtons.add(jRadioButtonSizeSmall);
        jRadioButtonSizeSmall.setSelected(true);
        jRadioButtonSizeSmall.setText("small");
        jRadioButtonSizeSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallButtonClicked(evt);
            }
        });

        SizeButtons.add(jRadioButtonSizeMedium);
        jRadioButtonSizeMedium.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonSizeMedium.setText("medium");
        jRadioButtonSizeMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumButtonClicked(evt);
            }
        });

        SizeButtons.add(jRadioButtonSizeLarge);
        jRadioButtonSizeLarge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonSizeLarge.setText("large");
        jRadioButtonSizeLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSizeLayout = new javax.swing.GroupLayout(jPanelSize);
        jPanelSize.setLayout(jPanelSizeLayout);
        jPanelSizeLayout.setHorizontalGroup(
            jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSizeSmall)
                    .addComponent(jRadioButtonSizeMedium)
                    .addComponent(jRadioButtonSizeLarge))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSizeLayout.setVerticalGroup(
            jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSizeLayout.createSequentialGroup()
                .addComponent(jRadioButtonSizeSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSizeMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSizeLarge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelStyle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelText)
                .addGap(30, 30, 30)
                .addComponent(jPanelFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelStyle.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxListener
        fontName = (String)this.jComboBoxFont.getSelectedItem();
        applyFont();
    }//GEN-LAST:event_ComboBoxListener

    private void SmallButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallButtonClicked
        fontSize = SMALL_SIZE;
        applyFont();
    }//GEN-LAST:event_SmallButtonClicked

    private void MediumButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumButtonClicked
        fontSize = MEDIUM_SIZE;
        applyFont();
    }//GEN-LAST:event_MediumButtonClicked

    private void LargeButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeButtonClicked
        fontSize = LARGE_SIZE;
        applyFont();
    }//GEN-LAST:event_LargeButtonClicked

    private void ItalicButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicButtonClicked
        fontStyle += (this.jCheckBoxStyleItalic.isSelected()) ? 
                +Font.ITALIC :
                -Font.ITALIC;
        applyFont();
        
    }//GEN-LAST:event_ItalicButtonClicked

    private void BoldButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoldButtonClicked
        fontStyle += (this.jCheckBoxStyleBold.isSelected()) ? 
                +Font.BOLD : 
                -Font.BOLD;
        applyFont();
    }//GEN-LAST:event_BoldButtonClicked
    
    private void applyFont() {
        this.jLabelText.setFont(new Font(fontName, fontStyle, fontSize));
        this.pack();
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public void display() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FontViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FontViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FontViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FontViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FontViewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SizeButtons;
    private javax.swing.JCheckBox jCheckBoxStyleBold;
    private javax.swing.JCheckBox jCheckBoxStyleItalic;
    private javax.swing.JComboBox jComboBoxFont;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JPanel jPanelFont;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSize;
    private javax.swing.JPanel jPanelStyle;
    private javax.swing.JRadioButton jRadioButtonSizeLarge;
    private javax.swing.JRadioButton jRadioButtonSizeMedium;
    private javax.swing.JRadioButton jRadioButtonSizeSmall;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}

